#!/usr/bin/env python3
"""Regenerate CATALOG.md and catalog.json from architectures/*/build.json.

Usage: python3 scripts/build_catalog.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIRED = ["id", "title", "category", "status", "summary", "systems", "tags"]


def load_builds():
    builds, errors = [], []
    for meta_path in sorted((ROOT / "architectures").glob("*/build.json")):
        folder = meta_path.parent.name
        try:
            meta = json.loads(meta_path.read_text())
        except json.JSONDecodeError as e:
            errors.append(f"{folder}: invalid JSON ({e})")
            continue
        missing = [k for k in REQUIRED if k not in meta]
        if missing:
            errors.append(f"{folder}: missing {', '.join(missing)}")
        if meta.get("id") != folder:
            errors.append(f"{folder}: id {meta.get('id')!r} does not match folder name")
        meta["path"] = f"architectures/{folder}"
        builds.append(meta)
    return builds, errors


def render_markdown(builds):
    lines = [
        "# Catalog",
        "",
        "Generated by `scripts/build_catalog.py` from each architecture's `build.json`. Do not edit by hand.",
        "",
    ]
    if not builds:
        lines.append("_No architectures yet._")
        return "\n".join(lines) + "\n"

    lines += [
        "| Architecture | Category | Summary | Required systems | Status |",
        "|--------------|----------|---------|------------------|--------|",
    ]
    for b in sorted(builds, key=lambda b: (b.get("category", ""), b["id"])):
        systems = ", ".join(b.get("systems", {}).get("required", []))
        lines.append(
            f"| [{b.get('title', b['id'])}]({b['path']}/) | {b.get('category', '')} "
            f"| {b.get('summary', '')} | {systems} | {b.get('status', '')} |"
        )

    lines += ["", "## By tag", ""]
    by_tag = {}
    for b in builds:
        for tag in b.get("tags", []):
            by_tag.setdefault(tag, []).append(b)
    for tag in sorted(by_tag):
        links = ", ".join(f"[{b['id']}]({b['path']}/)" for b in sorted(by_tag[tag], key=lambda b: b["id"]))
        lines.append(f"- **{tag}**: {links}")
    return "\n".join(lines) + "\n"


def main():
    builds, errors = load_builds()
    (ROOT / "catalog.json").write_text(json.dumps(builds, indent=2) + "\n")
    (ROOT / "CATALOG.md").write_text(render_markdown(builds))
    print(f"catalog: {len(builds)} architecture(s)")
    for e in errors:
        print(f"  WARN {e}")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
