#!/usr/bin/env python3
"""Regenerate CATALOG.md and catalog.json from architectures/<group>/<build>/build.json.

Usage: python3 scripts/build_catalog.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIRED = ["id", "title", "group", "status", "summary", "systems", "tags"]


def is_placeholder(value):
    return isinstance(value, str) and value.startswith("{{")


def load():
    groups, errors = [], []
    for group_path in sorted((ROOT / "architectures").glob("*/group.json")):
        group_dir = group_path.parent
        try:
            group = json.loads(group_path.read_text())
        except json.JSONDecodeError as e:
            errors.append(f"{group_dir.name}: invalid group.json ({e})")
            continue
        if group.get("id") != group_dir.name:
            errors.append(f"{group_dir.name}: group id {group.get('id')!r} does not match folder")
        group["path"] = f"architectures/{group_dir.name}"
        group["builds"] = []

        for meta_path in sorted(group_dir.glob("*/build.json")):
            folder = meta_path.parent.name
            where = f"{group_dir.name}/{folder}"
            try:
                meta = json.loads(meta_path.read_text())
            except json.JSONDecodeError as e:
                errors.append(f"{where}: invalid JSON ({e})")
                continue
            missing = [k for k in REQUIRED if k not in meta]
            if missing:
                errors.append(f"{where}: missing {', '.join(missing)}")
            if meta.get("id") != folder:
                errors.append(f"{where}: id {meta.get('id')!r} does not match folder")
            if meta.get("group") != group_dir.name:
                errors.append(f"{where}: group {meta.get('group')!r} does not match parent folder")
            meta["path"] = f"{group['path']}/{folder}"
            group["builds"].append(meta)
        groups.append(group)
    return groups, errors


def link(b):
    return f"[{b['id']}]({b['path']}/)"


def render_matrix(group):
    """Grid for groups with exactly two axes. A build fills a cell when both axis values appear in its id."""
    axes = list(group.get("axes", {}).items())
    if len(axes) != 2:
        return []
    (_, rows), (_, cols) = axes
    lines = ["| | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    for r in rows:
        cells = []
        for c in cols:
            match = next((b for b in group["builds"] if r in b["id"].split("-") and c in b["id"]), None)
            cells.append(f"{link(match)} · {match['status']}" if match else "—")
        lines.append(f"| **{r}** | " + " | ".join(cells) + " |")
    return lines + [""]


def render_markdown(groups):
    lines = [
        "# Catalog",
        "",
        "Generated by `scripts/build_catalog.py` from each group's `group.json` and each architecture's `build.json`. Do not edit by hand.",
        "",
        "Status: `stub` (folder only) → `draft` (documented, untested) → `tested` (ran end to end on a real environment) → `production` (running somewhere today).",
        "",
    ]
    if not groups:
        return "\n".join(lines + ["_No groups yet._"]) + "\n"

    lines += ["| Group | Architectures | Summary |", "|-------|---------------|---------|"]
    for g in groups:
        lines.append(f"| [{g['title']}](#{g['id']}) | {len(g['builds'])} | {g.get('summary', '')} |")
    lines.append("")

    for g in groups:
        lines += [f"## {g['title']}", ""]
        lines += [f"{g.get('summary', '')} Group docs: [{g['path']}/GROUP.md]({g['path']}/GROUP.md)", ""]
        if g.get("trigger_types"):
            lines += ["Trigger types: " + ", ".join(f"`{t}`" for t in g["trigger_types"]), ""]
        lines += render_matrix(g)
        lines += [
            "| Architecture | Platform | Destination | Summary | Status |",
            "|--------------|----------|-------------|---------|--------|",
        ]
        for b in sorted(g["builds"], key=lambda b: b["id"]):
            summary = "_not written yet_" if is_placeholder(b.get("summary")) else b.get("summary", "")
            platform = "" if is_placeholder(b.get("platform")) else b.get("platform", "")
            destination = "" if is_placeholder(b.get("destination")) else b.get("destination", "")
            lines.append(f"| {link(b)} | {platform} | {destination} | {summary} | {b.get('status', '')} |")
        lines.append("")
    return "\n".join(lines)


def main():
    groups, errors = load()
    (ROOT / "catalog.json").write_text(json.dumps(groups, indent=2) + "\n")
    (ROOT / "CATALOG.md").write_text(render_markdown(groups))
    total = sum(len(g["builds"]) for g in groups)
    print(f"catalog: {len(groups)} group(s), {total} architecture(s)")
    for e in errors:
        print(f"  WARN {e}")
    sys.exit(1 if errors else 0)


if __name__ == "__main__":
    main()
